### ISSUE TITLE
Not working when HN has condolence bar active

### ISSUE THREAD

**Issue by neXter** [mrspeaker/HackemUp#1]
If the black condolence header is active on Hacker News, the following is added as the first table row:

``` html
<tr><td bgcolor=#000000><img src="http://ycombinator.com/images/s.gif" height=5 width=0></td></tr>
```

In this case, the bookmarklet does not work.

**Comment by alimbada** [comment]
I've been noticing this too since the condolence bar has been up a few times this month.

**Comment by mrspeaker** [comment]
I thiiiink I fixed this. Closing for now.
